### ISSUE TITLE
[PE-D][Tester B] .jar file was updated on 2.50pm, past the feature freeze time

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-2/tp#162]
Picture taken at 4.17pm:
![image.png](https://raw.githubusercontent.com/Eola-Z/ped/main/files/60415d28-54d8-468b-9a97-721e151348c5.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Eola-Z/ped#3

**Comment by shishirbychapur** [comment]
Not a bug.
