### ISSUE TITLE
[PE-D][Tester A] Using JSON data with invalid fields cause LoveBook to silently clear data

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-2/tp#165]
User is not informed that data is invalid and that data is cleared when json file for list of dates is modified.

Steps
1. Modify the JSON file, e.g. M to m
2. Run the program.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: CJ-Lee01/ped#1

**Comment by shishirbychapur** [comment]
Fixed by PR #224. Updated UG to inform user that doing so will wipe the lovebook clean.
