### ISSUE TITLE
[PE-D][Tester C] Able to create a Date with a numerical name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-2/tp#177]
I was able to create a Date with the name `123`. Although this matches what is stated on the UG (argument must be a non-empty string), maybe inputting a fully numeric name can be prevented! (Although I can understand if alphanumeric strings are accepted by the app such as `XAEA-12`).

![image.png](https://raw.githubusercontent.com/jacobcuison/ped/main/files/12182b5e-cf04-4b04-a90d-59fd76973ce4.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jacobcuison/ped#5

**Comment by shishirbychapur** [comment]
Fixed by PR #224 . Updated UG to say "Name can include letters, spaces and numbers."
