### ISSUE TITLE
[PE-D][Tester D] UI: Text does not fill up full width of text box

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-2/tp#185]
The Date description always takes up two rows, no matter how much space there is to the right of the box.

![image.png](https://raw.githubusercontent.com/p-xp/ped/main/files/9a9c547d-0ea1-40dc-87ae-6da6b6e32cfe.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: p-xp/ped#11

**Comment by shishirbychapur** [comment]
Duplicate.
