### ISSUE TITLE
[PE-D][Tester C] Unable to sort by income

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-2/tp#197]
The commands `sort income/increasing` and `sort income/decreasing` did not do anything. In the screenshot below, the Date `def` should be the very last one since it has the highest income...

![image.png](https://raw.githubusercontent.com/jacobcuison/ped/main/files/b16866ea-4c05-49f3-9c4e-6e398194128b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jacobcuison/ped#10

**Comment by lynnlow175** [comment]
This issue was due to the use of parseInt which only accepts values up to 10 digits. I have fixed it by using parseLong instead!
