### ISSUE TITLE
[PE-D][Tester B] Incorrect Information in summary tab

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-2/tp#217]
I believe this is meant to say `bestMatch` instead of `match`?

![image.png](https://raw.githubusercontent.com/Eola-Z/ped/main/files/b0a0f8c4-1c35-45a5-9dd6-518328af3e8a.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Eola-Z/ped#14

**Comment by shishirbychapur** [comment]
Fixed by PR #223
