### ISSUE TITLE
[PE-D][Tester E] bestMatch does not work for some instances

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-2/tp#218]
![image.png](https://raw.githubusercontent.com/peiran18/ped/main/files/1213ea1a-9b91-4734-9573-e94725fcbaee.png)

when a new person with a very big income value is added, the bestMatch command does not work afterwards.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: peiran18/ped#8

**Comment by bobscodedump** [comment]
maybe fixed after we add validation to income field?

**Comment by Cleon2** [comment]
Added validation to deny excessive income entries that can mess up best match
