### ISSUE TITLE
[PE-D][Tester D] UG: Typo under `find` section

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-2/tp#219]
Just a minor note.

![image.png](https://raw.githubusercontent.com/p-xp/ped/main/files/603bc97c-f859-4b70-b1b8-184b2d1f6f3d.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: p-xp/ped#21

**Comment by shishirbychapur** [comment]
Fixed by PR #220
